-- Backup existing data
CREATE TABLE users_backup AS SELECT * FROM users;
CREATE TABLE don_ung_tuyen_backup AS SELECT * FROM don_ung_tuyen;

-- Drop existing tables and constraints
DROP TABLE user_roles;
DROP TABLE roles;
DROP TABLE don_ung_tuyen;
DROP TABLE users;

-- Create tables with updated schema
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    enabled NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(20) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE don_ung_tuyen (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    vi_tri VARCHAR2(100) NOT NULL,
    ho_ten VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    so_dien_thoai VARCHAR2(20) NOT NULL,
    dia_chi VARCHAR2(200) NOT NULL,
    ngay_sinh DATE NOT NULL,
    gioi_tinh VARCHAR2(10) NOT NULL,
    trinh_do_hoc_van VARCHAR2(50) NOT NULL,
    kinh_nghiem VARCHAR2(2000),
    ky_nang VARCHAR2(2000),
    quyen_test NUMBER(1) DEFAULT 0,
    trang_thai VARCHAR2(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Insert default roles
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');
INSERT INTO roles (name) VALUES ('ROLE_RECRUITER');
INSERT INTO roles (name) VALUES ('ROLE_HR_STAFF');
INSERT INTO roles (name) VALUES ('ROLE_CV_STAFF');
INSERT INTO roles (name) VALUES ('ROLE_CANDIDATE');

-- Restore data from backup
INSERT INTO users (id, username, email, password, first_name, last_name, enabled, created_at, updated_at)
SELECT id, username, email, password, 'Unknown', 'Unknown', enabled, created_at, updated_at
FROM users_backup;

INSERT INTO don_ung_tuyen (id, user_id, vi_tri, ho_ten, email, so_dien_thoai, dia_chi, ngay_sinh, gioi_tinh, 
                          trinh_do_hoc_van, kinh_nghiem, ky_nang, quyen_test, trang_thai, created_at, updated_at)
SELECT id, user_id, vi_tri, ho_ten, email, so_dien_thoai, dia_chi, ngay_sinh, gioi_tinh, 
       trinh_do_hoc_van, kinh_nghiem, ky_nang, quyen_test, trang_thai, created_at, updated_at
FROM don_ung_tuyen_backup;

-- Drop backup tables
DROP TABLE users_backup;
DROP TABLE don_ung_tuyen_backup;

-- Create indexes
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_don_ung_tuyen_user_id ON don_ung_tuyen(user_id);
CREATE INDEX idx_don_ung_tuyen_trang_thai ON don_ung_tuyen(trang_thai); 